- name: Install nfs
  yum:
    name: nfs-utils
    state: present
- name: start and enable nfs
  service:
    name: nfs-server.service
    state: started
    enabled: true

- name: create a directory for nfs mounts
  become: no
  file:
        path: /home/ec2-user/statefulset/nfs
        state: directory
        mode: '0755' 
        recurse: yes

- name: Ensure mongo-0 directory
  become: no
  file:
        path: /home/ec2-user/statefulset/nfs/mongo-0
        state: directory
        mode: '0755' 
- name: Ensure mongo-1 directory
  become: no
  file:
        path: /home/ec2-user/statefulset/nfs/mongo-1
        state: directory
        mode: '0755' 

- name: Ensure mongo-2 directory
  become: no
  file:
        path: /home/ec2-user/statefulset/nfs/mongo-2
        state: directory
        mode: '0755' 
- name: Add exports entry for NFS directory
  lineinfile:
        path: /etc/exports
        line: "/home/ec2-user/statefulset/nfs *(rw,sync,no_root_squash)"
        create: yes
        state: present
        insertafter: EOF
- name: Export NFS shares
  command: exportfs -rv