

- name: Install git
  yum:
    name: git
    state: present
- name: Install nfs
  yum:
    name: nfs-utils
    state: present
- name: start and enable nfs
  service:
    name: nfs-server.service
    state: started
    enabled: true
- name: Clone GitOps repo
  git:
    repo: "https://github.com/AbdallahElaraby/Todo-List-nodejs-GitOps.git"
    dest: "/opt/todo-list-gitops"
    force: yes

- name: Apply ArgoCD manifests
  become: false
  shell:  /usr/local/bin/kubectl apply -f /opt/todo-list-gitops/argocd/application.yaml
  register: apply_output

- name: Retrieve ArgoCD admin password
  become: false
  shell: |
    /usr/local/bin/kubectl -n argocd get secret argocd-initial-admin-secret \
    -o jsonpath="{.data.password}" | base64 -d
  register: admin_password

- name: Show ArgoCD admin password
  debug:
    msg: "ArgoCD admin password is: {{ admin_password.stdout }}"
