
- name: Check if Minikube is already installed
  stat:
    path: /usr/local/bin/minikube
  register: minikube_stat

- name: Download Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'
  when: not minikube_stat.stat.exists

- name: Check if Minikube has been initialized
  stat:
    path: /home/{{ ansible_user }}/.minikube
  register: minikube_home

- name: Start Minikube with docker driver
  shell: sg docker -c "minikube start --driver=docker"
  become: false
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  args:
    executable: /bin/bash
  when: not minikube_home.stat.exists

- name: Create patched metrics-server manifest
  shell: |
    curl -sL https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml | \
    sed 's/args:/args:\n        - --kubelet-insecure-tls/' > /tmp/metrics-server-patched.yaml
  args:
    executable: /bin/bash
  become: false

- name: Install metrics server with TLS verification disabled
  shell: |
    export KUBECONFIG=/home/{{ ansible_user }}/.kube/config
    kubectl apply -f /tmp/metrics-server-patched.yaml --validate=false
  args:
    executable: /bin/bash
  become: false

- name: Verify metrics-server is healthy
  shell: |
    kubectl wait --for=condition=Ready pod -l k8s-app=metrics-server -n kube-system --timeout=180s
  args:
    executable: /bin/bash
  become: false