- name: Run docker command via newgrp
  become: false
  shell: |
    newgrp docker <<EOF
    docker info
    EOF


- name: Check if Minikube is already installed
  stat:
    path: /usr/local/bin/minikube
  register: minikube_stat

- name: Download Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'
  when: not minikube_stat.stat.exists

- name: Check if Minikube has been initialized
  stat:
    path: /home/{{ ansible_user }}/.minikube
  register: minikube_home

- name: Start Minikube with docker driver
  shell: sg docker -c "minikube start --driver=docker"
  become: false
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  args:
    executable: /bin/bash
  when: not minikube_home.stat.exists

