- name: Install Docker
  yum:
    name: docker
    state: present

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
- name: Print post-install reminder
  debug:
    msg: |
      Docker is installed and your user was added to the docker group.
      Run 'newgrp docker' or log out and log back in for changes to take effect.
- name: Confirm docker group is active in shell
  become: true
  shell: |
    sg docker -c "docker version"
  register: docker_group_test
  ignore_errors: true

- name: Show docker group access result
  debug:
    var: docker_group_test.stdout_lines
